#let titleEnglish = "Improving Stability of Web Applications by Optimized E2E Testing"
#let titleGerman = "Verbesserung der Stabilität von Webanwendungen durch Optimierte E2E-Tests"
#let degree = "Master"
#let program = "Informatics"
#let supervisor = "Prof. Dr. Stephan Krusche"
#let advisors = "Prof. Dr. Stephan Krusche"
#let author = "(Murad Talibov)"
#let startDate = datetime(day: 15, month: 12, year: 2023)
#let submissionDate = datetime(day: 15, month: 6, year: 2024)